#!/bin/bash

# BlockTrace Full Stack Development Startup Script
# Starts all three services: Blockchain node, Backend server, Frontend app

echo "==========================================="
echo "   BlockTrace Full Stack Startup Guide"
echo "==========================================="
echo ""
echo "This script will help you start all services."
echo "Open 3+ terminal windows and follow the steps below:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 1: Start Hardhat Local Node"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd blockchain"
echo "  npm install             # First time only"
echo "  npm run node"
echo ""
echo "⏸️  WAIT — Copy the RPC URL (should be: http://127.0.0.1:8545)"
echo "   Then proceed to Terminal 2"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 2: Deploy Smart Contract"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd blockchain"
echo "  npm run deploy:local"
echo ""
echo "⏸️  WAIT — Copy the CONTRACT_ADDRESS from output"
echo "   Example output:"
echo "      SupplyChainRegistry: 0x1234567890..."
echo "      PriceRangeVerifier: 0xabcdef..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "UPDATE BACKEND CONFIG"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Edit backend/.env and set:"
echo "    BLOCKCHAIN_RPC=http://127.0.0.1:8545"
echo "    CONTRACT_ADDRESS=0x...  (from Terminal 2)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 3: Start Backend Server"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd backend"
echo "  npm install                    # First time only"
echo "  npm start"
echo ""
echo "✓ Backend runs on http://localhost:3000"
echo "  API: http://localhost:3000/api/auth/login (POST)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "UPDATE FRONTEND CONFIG"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Edit frontend/.env and set:"
echo "    VITE_API_URL=http://localhost:3000"
echo "    VITE_PRICE_VERIFIER_ADDRESS=0x...  (from Terminal 2)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 4: Start Frontend (Dev Server)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd frontend"
echo "  npm install                    # First time only"
echo "  npm run dev"
echo ""
echo "✓ Frontend runs on http://localhost:5173"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 FULL STACK READY!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Access the app: http://localhost:5173"
echo ""
echo "Test Users (register or use existing):"
echo "  - Manufacturer: mfg@example.com"
echo "  - Distributor: dist@example.com"
echo "  - Retailer: retail@example.com"
echo "  - Admin: admin@example.com"
echo ""
echo "Password (default): password123"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Running Tests"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend tests:"
echo "  cd backend && npm test"
echo ""
echo "Blockchain tests:"
echo "  cd blockchain && npm test"
echo ""
echo "Expected: All tests passing (57 backend + 15+ blockchain)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 API Documentation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Import Postman collection: docs/BlockTrace.postman_collection.json"
echo "Architecture diagram: docs/architecture.md"
echo ""
echo "✅ Happy coding!"
